name: Filter Compiler

on:
  schedule:
    - cron: '0 */12 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2.5.1
      with:
        node-version: '14'  
    - run: npm i -g @adguard/hostlist-compiler
    
    - name: Compile Lite list
      run: hostlist-compiler -c ./source/extra.json -o extra.txt
    
    - name: Compile Main list
      run: hostlist-compiler -c ./source/fukuro.json -o filter.txt
    
    - name: Commit changes
      uses: EndBug/add-and-commit@v8
      with:
        default_author: github_actions
    
    - name: Delete workflow runs
      uses: GitRML/delete-workflow-runs@main
      with:
        retain_days: 1
        keep_minimum_runs: 1
