name: Filter Compiler

on:
  schedule:
    - cron: '0 23 */1 * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: '16'  
    - run: npm i -g hostlist-compiler-ozonep
    
    - name: Compile Main list
      run: hostlist-compiler -c ./source/lite.json -o filter.txt

    - name: Compile Schakal list
      run: hostlist-compiler -c ./source/schakal.json -o schakal.txt
         
    - name: Commit changes
      uses: EndBug/add-and-commit@v9
      with:
        default_author: github_actions
    
    - name: Delete workflow runs
      uses: GitRML/delete-workflow-runs@main
      with:
        retain_days: 1
        keep_minimum_runs: 1
